name: tortoisegit-portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-2019
    env:
      targetZip: tortoisegit-portable-${{ github.ref_name }}.zip
    steps:
      - name: installer
        shell: cmd
        run: |
          curl https://www.apple.com/itunes/download/win64 -L --output installer.exe &&^
          7z.exe x installer.exe &&^
          dir
          
      - name: lessmsi 
        shell: cmd
        run: | 
          curl https://github.com/activescott/lessmsi/releases/download/v1.10.0/lessmsi-v1.10.0.zip -L --output lessmsi.zip && 7z.exe x lessmsi.zip -o"lessmsi"
          
      - name: uncompress iTunes64.msi
        shell: cmd
        run: |
          .\lessmsi\lessmsi.exe x "iTunes64.msi" "iTunes64-installation\"
          
      - name: uncompress Bonjour64.msi
        shell: cmd
        run: |
          .\lessmsi\lessmsi.exe x "Bonjour64.msi" "Bonjour64-installation\"
          
      - name: copy files from bonjour
        shell: cmd
        run: |
          copy "Bonjour64-installation\SourceDir\dnssd.dll.duplicate1" "iTunes64-installation\SourceDir\iTunes\dnssd.dll" &&^
          copy "Bonjour64-installation\SourceDir\dnssdX.dll.duplicate1" "iTunes64-installation\SourceDir\iTunes\dnssdX.dll" &&^
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "iTunes64-installation/SourceDir/iTunes"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "iTunes64-installation/SourceDir/iTunes/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
